### ISSUE TITLE
Hello dude can you make exe file

### ISSUE THREAD

**Issue by TrustedPeople** [noedigcode/Kanbanapp#1]
Hello can you make the exe file please i need this app too much i dont understant how this qt works it dont make the exe file i too stupid to use this thing properly please help

**Comment by noedigcode** [comment]
I'm so sorry for the late reply. Somehow GitHub didn't let me know of your issue or I just missed it.
I just made a release. Under releases, download the zip file, extract everything, and run the exe. The rest of the DLL files in must also be extracted and remain in the same folder as the exe file.
